name: flutter_web_portfolio
description: "Nijat Naghiyev's Flutter Web Portfolio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Web Support
  web: ^1.1.1

  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  equatable: ^2.0.8

  # Firebase
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.2
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  # Navigation
  go_router: ^17.1.0

  # Dependency Injection
  get_it: ^9.2.1
  injectable: ^2.7.1+4

  # Utilities
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  flutter_svg: ^2.2.3
  url_launcher: ^6.3.2


  # Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.11.1
  injectable_generator: ^2.12.0

  # Serialization
  freezed: ^3.2.5
  json_serializable: ^6.13.0


  # Linting
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/static/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/static/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/static/Inter_18pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/static/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/static/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/static/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
          weight: 900
