name: flutter_web_portfolio
description: "Nijat Naghiyev's Flutter Web Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  flutter:
    sdk: flutter
  freezed: ^3.2.5
  get_it: ^9.2.0
  go_router: ^17.1.0
  injectable: ^2.7.1+4
  json_serializable: ^6.12.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.11.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^3.1.0
  injectable_generator: ^2.12.0
  json_annotation: ^4.10.0
  very_good_analysis: ^10.1.0

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
